// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDofoZpOu6kZn_XajfsbzwVzD_RM27sCg',
    appId: '1:79748707845:android:c884ac03295853cccbce6c',
    messagingSenderId: '79748707845',
    projectId: 'lelang-53c84',
    storageBucket: 'lelang-53c84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbd_KoJOBNxnNW4XJ6ijv5_pQwQ4QzgIA',
    appId: '1:79748707845:ios:58a671c456462560cbce6c',
    messagingSenderId: '79748707845',
    projectId: 'lelang-53c84',
    storageBucket: 'lelang-53c84.appspot.com',
    androidClientId: '79748707845-shilb3dni4fsla82m66eeriel7fukfb6.apps.googleusercontent.com',
    iosClientId: '79748707845-vvpuu8ijp92v14s0cc65831muj6n04q4.apps.googleusercontent.com',
    iosBundleId: 'com.lastcall.apps',
  );

}